[package]
name = "get-nft-collection-holders"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.20", features = ["json"] }
serde_json = "1.0.106"
tokio =  { version = "1.5.0", features = ["full"] }
dotenv = "0.15.0"
